#!/usr/bin/env python3
"""
Build the skill taxonomy from the question bank.

Emits data/skills.json and supabase/seed_skills.sql. The per-skill, per-tier
item counts become the "how often does this appear on the test" term in the
selection formula, so this is not just a label table - it carries weight.

The bank also exposes score_band_range_cd (1-7), College Board's own finer
difficulty banding underneath the E/M/H code. We keep the distribution per
skill: it is strictly more information than the three-way split and gives the
engine somewhere to go if E/M/H proves too coarse.
"""
import json, os
from collections import defaultdict, Counter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BANK = os.path.join(ROOT, "corpus", "bank")

SECTION_OF = {"INI": "rw", "CAS": "rw", "EOI": "rw", "SEC": "rw",
              "H": "math", "P": "math", "Q": "math", "S": "math"}
TIERS = ["E", "M", "H"]


def sql_quote(s):
    return "null" if s is None else "'" + str(s).replace("'", "''") + "'"


def main():
    skills = defaultdict(lambda: {
        "counts": Counter(), "bands": Counter(),
        "domain_cd": None, "domain_name": None, "skill_name": None})

    missing = []
    for domain, section in SECTION_OF.items():
        path = os.path.join(BANK, domain, "_listing.json")
        if not os.path.exists(path):
            missing.append(domain)
            continue
        for it in json.load(open(path)):
            cd = it.get("skill_cd")
            if not cd:
                continue
            s = skills[cd]
            s["domain_cd"]   = it.get("primary_class_cd") or domain
            s["domain_name"] = it.get("primary_class_cd_desc")
            s["skill_name"]  = it.get("skill_desc")
            s["section"]     = section
            tier = (it.get("difficulty") or "").upper()
            if tier in TIERS:
                s["counts"][tier] += 1
            band = it.get("score_band_range_cd")
            if band is not None:
                s["bands"][str(band)] += 1

    section_totals = Counter()
    for s in skills.values():
        section_totals[s["section"]] += sum(s["counts"].values())

    out = []
    for cd, s in sorted(skills.items()):
        total = sum(s["counts"].values())
        out.append({
            "skill_cd": cd,
            "domain_cd": s["domain_cd"],
            "section": s["section"],
            "domain_name": s["domain_name"],
            "skill_name": s["skill_name"],
            "bank_count_e": s["counts"]["E"],
            "bank_count_m": s["counts"]["M"],
            "bank_count_h": s["counts"]["H"],
            "bank_total": total,
            # Denominator for skillFrequency() in the engine.
            "section_total": section_totals[s["section"]],
            "score_bands": dict(sorted(s["bands"].items())),
        })

    os.makedirs(os.path.join(ROOT, "data"), exist_ok=True)
    with open(os.path.join(ROOT, "data", "skills.json"), "w") as fh:
        json.dump({"skills": out,
                   "section_totals": dict(section_totals),
                   "incomplete_domains": missing}, fh, indent=1)

    lines = ["-- Generated by tools/build_skills.py. Do not edit by hand.",
             "-- Load with the service key; the anon role cannot write this table.", ""]
    for s in out:
        lines.append(
            "insert into public.skills (skill_cd, domain_cd, section, domain_name, "
            "skill_name, bank_count_e, bank_count_m, bank_count_h) values ("
            f"{sql_quote(s['skill_cd'])}, {sql_quote(s['domain_cd'])}, "
            f"{sql_quote(s['section'])}, {sql_quote(s['domain_name'])}, "
            f"{sql_quote(s['skill_name'])}, {s['bank_count_e']}, "
            f"{s['bank_count_m']}, {s['bank_count_h']})\n"
            "on conflict (skill_cd) do update set "
            "domain_cd = excluded.domain_cd, section = excluded.section, "
            "domain_name = excluded.domain_name, skill_name = excluded.skill_name, "
            "bank_count_e = excluded.bank_count_e, bank_count_m = excluded.bank_count_m, "
            "bank_count_h = excluded.bank_count_h;")
    with open(os.path.join(ROOT, "supabase", "seed_skills.sql"), "w") as fh:
        fh.write("\n".join(lines) + "\n")

    if missing:
        print(f"! not yet downloaded: {', '.join(missing)} - rerun when the fetch finishes\n")
    print(f"{'skill':10} {'section':8} {'E':>5} {'M':>5} {'H':>5} {'tot':>6}  name")
    for s in out:
        print(f"{s['skill_cd']:10} {s['section']:8} {s['bank_count_e']:5} "
              f"{s['bank_count_m']:5} {s['bank_count_h']:5} {s['bank_total']:6}  {s['skill_name']}")
    print(f"\n{len(out)} skills, {sum(s['bank_total'] for s in out)} items")
    print("wrote data/skills.json and supabase/seed_skills.sql")


if __name__ == "__main__":
    main()
